apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-content
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Mi
  csi: {}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: "hostpath"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: cms-content
  storageClassName: "hostpath"