#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: cms-content
#spec:
#  accessModes:
#  - ReadWriteMany
#  capacity:
#    storage: 200Mi
#  csi: {}
#  persistentVolumeReclaimPolicy: Retain
#  volumeMode: Filesystem
#  storageClassName: "hostpath"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: cms-content-volume
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 200Mi
#  volumeName: cms-content
#  storageClassName: "hostpath"

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-content
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: hostpath
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: cms-content
  storageClassName: "hostpath"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: Module-content
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: hostpath
  hostPath:
    path: /mnt/Modules
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: Module-content-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: Module-content
  storageClassName: "hostpath"