#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: cms-content
#spec:
#  accessModes:
#  - ReadWriteMany
#  capacity:
#    storage: 200Mi
#  csi: {}
#  persistentVolumeReclaimPolicy: Retain
#  volumeMode: Filesystem
#  storageClassName: "hostpath"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: cms-content-volume
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 200Mi
#  volumeName: cms-content
#  storageClassName: "hostpath"

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-content
spec:
  nodeSelector:
    kubernetes.io/hostname: docker-desktop
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: blob-premium
  local:
    fsType : ext4
    path: /mnt/data
  #nodeAffinity:
  #  required:
  #    nodeSelectorTerms:
  #    - matchExpressions:
  #      - key: kubernetes.io/os
  #        operator: In
  #        values:
  #        - linux

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: cms-content
  storageClassName: "blob-premium"