apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
- ../../../common-base
namePrefix: virtonew-
commonLabels:
  instance: virtonew
  
resources:
- base/virtonew-app.yaml